### ISSUE TITLE
Eggborn and Tiny issue

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#10]
_Bug report forwarded from steam workshop_
Reportee: **Them8**
tiny and eggborn has an issue... it adds to build time instead of decreasing it.

**Comment by LuxArdens** [comment]
Speed modifier completely gone it seems. Cost modifier still works. Increased the cost bonus slightly and replaced the speed bonus with colony development speed.

**Comment by TvoEx** [comment]
The speed bonus is still there, it just works with negitive numbers now, Where as before 4 meant 400% faster now it just multiplies the time by 4, thus -0.75 should reduce it to the appropriate amount.

**Comment by TvoEx** [comment]
But then, if I were to do that, combined with Tiny having a -0.25 and Eggborn -0.75, you would literally get 0 time to make ships, granted they still cost 150 minerals, which for tiny races is quite allot actually

**Comment by LuxArdens** [comment]
Tiny+Eggborn currently makes colony ships completely free. That's a bit nonsensical granted, but giving them enough modifiers to get -90% cost would still mean they end up with free colony ships after the first tech for reduced costs comes up anyway, so I'm not too eager to try and make it perfect because it's probably a bit impossible. Free colony ships were actually more powerful before 2.0 anyway, because everyone is outpost limited now.
