### ISSUE TITLE
Syncretic species and rogue servitor secondary species

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#28]
If you applied, say titanic on them, you would get massively powerful slaves without the empire buffs and debuffs, In my opinion this is fine as is, why should the mod limit people from having titanic slaves.

While the empire modifiers aren't used as the main species isn't titanic, the slaves still have all the trait modifiers of buffs and debuffs, they still take 10 times longer to grow, consume 500% more food and consumer goods.

**Comment by TvoEx** [comment]
But this is your mod, so you have the final say.

**Comment by LuxArdens** [comment]
Titanic cannot be added through genemodding, and cannot be 'picked' for syncretic species, so this 'problem' is invalid. In fact, I believe that currently, playing as a Titanic species with the Syncretic civic, you get a subservient species that _doesn't_ have the Titanic trait and is thus fairly useless to you.

It's still very powerful to conquer a (primitive) Titanic species and use them as Mineral slaves though, but I agree that that's pretty much fine. I _would_ make it so that the buildings those slaves use are more expensive, but there's no way to do that and I greatly prefer such a minor advantage over completely locking down the possibility.
