### ISSUE TITLE
Request from the workshop

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#32]
_Forwarded from steam workshop_
From: **Alpha Titan**
I see that, the problem was the window was moving so that i couldn't see the top half of the selection screen but it seems resolved now.

On a different note i was wondering if there would be a way to not make the cheating +99 trait and the -20/-40/-60 trait point penalties mutally exclusive? I want to make some cool genetic evolution species but if they have 78 extra trait points left over. I want them to be able to adapt throught he game and not instantly become perfect at everything instead of using the trait points that they earn via reaserch/perks in game and i want to use those handicap traits to "soak" up the extra points. Ora as an alternative you might allow a moderate +20/40/60 ect trait so theres a middleground on how many points to use. I love the RPness of the mod by the way! 

And one final point thats more of a question, the obsessed with armor trait removes shields, but obsessed with shilds decreases hull, not armor. Is that on purrpose?

**Comment by TvoEx** [comment]
That last part, kind of has a point, OWS reduced hull before, but now armor is basically hitpoints, why not make it void armor completely.

**Comment by LuxArdens** [comment]
#1 is because I was messing with the interface. A shorter trait view has been requested by multiple people using <720p screens. As a compromise to them, I made the screen movable again. The reporter probably just had a weird intra-fix version of the mod.

#2 is fair enough. The exclusions aren't really necessary. I might see about adding more bonuses, but I want to avoid cluttering the list

#3 not on purpose but I'm going to rebalance it anyway so I'll fix that too. I did the math and Armour is still 75% stronger than Shield obsessed in a straight up fight, and does not require energy either.
