### ISSUE TITLE
Organic Titanic races lacking 5x power generation

### ISSUE THREAD

**Issue by TvoEx** [LuxArdens/Stellaris---RPG-Traits-mod#33]
Machine ones work a bit Too well though, with 5x to unity and science.

**Comment by LuxArdens** [comment]
Intentional. Energy has changed meaning as mentioned earlier. Higher building upkeep was removed as well, so that shouldn't be a problem. Ship upkeep is still X5 or 4 or something, because I can't split upkeep into minerals and energy, but reducing it to <4 would be nonsensical anyway because their ships are 5 times as large and _should_ require 5 times the energy.

Machines being extremely easy to exploit into mad high production numbers was foreseen, but I'm still undecided on what to actually do about it without making robo-traits a watered down boring version of Organic traits.

**Comment by TvoEx** [comment]
I asked because building prices indicate massive structures, which would imply larger generators to satisfy greater need. It simply made sense, bigger and more expensive power plants = more power.

**Comment by LuxArdens** [comment]
That does make sense yes, but my rationale is that Titanic species also need all of that extra "power" (or organization) to run those buildings, and organize all of their other massive things.

Or approaching it from the other side: I did a quick Titanic testplay back when they still had their energy bonuses and it completely destroyed the balance, because all the other traits had had their energy bonuses nerfed. They could spam leaders and armies like nothing and it made me decide to bring them in line with the recent change in design.

**Comment by TvoEx** [comment]
This actually brings up a different point, Tiny races, they are strong, really strong, give them genius from the negative points Tiny costs and they can out-science literally any space faring empire by mass science planets and AI doesn't dare invade because fleet capacity regardless of how tiny their fleet actually is.

**Comment by LuxArdens** [comment]
Yea I gave them the negative cost a while back, but I didn't know the AI views them as such a threat. I'll revert the cost to zero. I still need to remove their energy penalties anyway, so I'll improve the entire package where necessary.

Taking a <not so negative trait>+genius is always an option though, and I've taken a very straight-forward "not-my-problem" approach to people min-maxing this mod. Similarly, having no actual fleet and intimidating the AI into protectorates is really a cheesy tactic.
