### ISSUE TITLE
Can you upload Core 2.1 version please?

### ISSUE THREAD

**Issue by dtndmd** [LuxArdens/Stellaris---RPG-Traits-mod#55]
Thank you very much

**Comment by TvoEx** [comment]
This was posted 2 days ago, why am I seeing this now? Anyways. 

After some minor dumpster diving into recycling bin I have found what I hope is the correct version, though I really should've seen this coming and archived it because people also asked for the same thing when 2.0 dropped.

[Direct link to RPGT 2.1](https://steamcommunity.com/sharedfiles/filedetails/?id=1608724897)
